### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by mcintyre321** [oexenhave/SirenSharp#1]
It would be great to have this on Nuget

**Comment by mcintyre321** [comment]
I've forked the project and pushed a library to nuget -https://www.nuget.org/packages/SirenSharp/ 

If you'd like to take control of this, please let me know.

**Comment by oexenhave** [comment]
Really cool. I'm struggling to find a project where it makes sense to use Siren in my daily work. Hopefully soon it will be possible. I could easily add you as collaborator to this repo if you are interested.

**Comment by mcintyre321** [comment]
I've been making breaking changes to SirenSharp, and I feel a bit naughty publishing the changes to NUget as SirenSharp. I could fork and rename my own work to SirenDotNet if you like, or continue under the SirenSharp name if you don't mind.

Not sure who else is using it TBH!
